### ISSUE TITLE
curious about workflow

### ISSUE THREAD

**Issue by kylemac** [jsebfranck/contentful-publication#5]
hey @jsebfranck, I came here from this post - https://www.contentful.com/blog/2015/02/11/how-to-sync-spaces-in-contentful/ and I had a question about your workflow. What I'm most curious about is what prompts the promotion from "editing space" to "production space" -- is this manually done by a developer or do you use `contentful-publication` in some other abstracted way so that folks from Xebia can promote content? 

Also, i'm happy to take this to email if you think it's more appropriate: kyle [at] carrotcreative.com

**Comment by jvinai** [comment]
Hello @kylemac ,

Our workflow is :
Marketing team create contents in "editing space" and when they want to do an "editorial release" they use the script to synchronise "editing space" to "production space".

**Comment by kylemac** [comment]
Right, so the workflow depends on the marketing team using the CLI, right?

**Comment by jvinai** [comment]
We create a jenkins job for them, they don't know what is a command line.
There are the main user of this script yes.

**Comment by kylemac** [comment]
ahh very cool! that's what I was hoping to do - avoid asking non-developers to know how to run a script or install node on their machine. 

so what is the interface that you expose to the user to allow them to trigger the Jenkins build? 

Hope you don't mind me asking so many questions

**Comment by jvinai** [comment]
We create a tab with "editorial tasks" and they using a specific user who just have access to this tab.

**Comment by kylemac** [comment]
so if you're building static output, what mechanism are you using for auth to allow validation of _"specific user who just have access"_? 

do you mind if I ask which build tool you're using to compile the static site currently?

**Comment by jvinai** [comment]
No no, Contentful give us metadatas of each pages and the pages are made by the server.

We using cache for Contentful call and we have a jenkins job when marketing team what to flush it (after a synch for example)

**Comment by kylemac** [comment]
Okay, I think what you're saying is that you give them access to the Jenkins admin and allow them to build it from there. Got it! Thanks for the discussion. We're looking forward to using `contentful-publication`
